language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"
install:
  - pip install codecov
script:
  - pytest test.py
  - coverage run test.py
after_success:
  - codecov
branches:
  only:
  - main
jobs:
  allow_failures:
  - python: "3.6"
  fast_finish: true